### PR TITLE
May 2018 logo update

### PR DESCRIPTION
**Pull request by chalin**
cc @kwalrath

### CODE REVIEW

**Comment by devoncarew** [comment]
I think we should land this, given that the master branch doesn't have the latest logo, and people do use this repo as the system of record for icons + images.

@filiph @kwalrath

**Comment by chalin** [comment]
This was closed w/o merging, probably not what you intended ...?

**Comment by kevmoo** [comment]
Sorry!

**Comment by chalin** [comment]
Np, it's happened to me too :)

**Comment by kevmoo** [comment]
@chalin careful deleting/renaming images – https://github.com/dart-lang/angular/issues/1338

**Comment by chalin** [comment]
Oups! My bad. I didn't think that folks would refer directly to images in the repo, but I suppose that it makes sense when linking from pages like GH README files. Would you like for me to setup symlinks for the main image files? Or maybe add a disclaimer that paths and/or images may change?

**Comment by kevmoo** [comment]
A symlink might be good. We'll fix the readme for future releases, but
older releases (on pub site) will still point to the old one.

A disclaimer in the readme would be good, too!

**Comment by kevmoo** [comment]
@chalin see https://github.com/dart-lang/logos/pull/5

**Pull request merged**
